# Generated by Django 5.0.7 on 2024-12-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmer',
            name='franchise_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dsausers',
            name='dsa_registerid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='franchisecode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='franchiseusers',
            name='franchise_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='registerid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
