# Generated by Django 4.2.16 on 2024-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_custmer_franchise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Backendemployee', 'Loan Process Backend'), ('Accounts', 'Accounts'), ('customersupport', 'Customer Support')], max_length=20),
        ),
    ]
